ALTER TABLE Account drop CONSTRAINT fk_matricola;
ALTER TABLE Finanziamento drop CONSTRAINT fk_bando;
ALTER TABLE Finanziamento drop CONSTRAINT fk_bene;
ALTER TABLE Dotazione drop CONSTRAINT fk_dipendente;
ALTER TABLE Dotazione drop CONSTRAINT fk_bene_dotazione;
ALTER TABLE Assegnazione drop CONSTRAINT fk_gruppo_di_lavoro;
ALTER TABLE Assegnazione drop CONSTRAINT fk_bene_assegnazione;
ALTER TABLE Richiesta drop CONSTRAINT fk_matricola_rich;
ALTER TABLE Richiesta drop CONSTRAINT fk_sotto_cat_bene_rich;
ALTER TABLE Allocazione drop CONSTRAINT fk_matr_all;
ALTER TABLE Allocazione drop CONSTRAINT fk_grup_di_lav_all;
ALTER TABLE Ubicazione drop CONSTRAINT fk_bene_ubicazione;
ALTER TABLE Ubicazione drop CONSTRAINT fk_stanza;
ALTER TABLE Postazione drop CONSTRAINT fk_matricola_postazione;
ALTER TABLE Postazione drop CONSTRAINT fk_stanza_postazione;
ALTER TABLE SottoCategoriaBene drop CONSTRAINT fk_categoria_bene;
ALTER TABLE Bene drop CONSTRAINT fk_sotto_categoria_bene;
ALTER TABLE Bene drop CONSTRAINT fk_fornitore;

DROP TABLE Account;
DROP TABLE Finanziamento;
DROP TABLE Dotazione;
DROP TABLE Assegnazione;
DROP TABLE Richiesta;
DROP TABLE Allocazione;
DROP TABLE Ubicazione;
DROP TABLE Postazione;
DROP TABLE Personale;
DROP TABLE Fornitore;
DROP TABLE CategoriaBene;
DROP TABLE Bando;
DROP TABLE GruppoDiLavoro;
DROP TABLE Stanza;
DROP TABLE SottoCategoriaBene;
DROP TABLE Bene;